import type { NextPage } from 'next';
import Head from 'next/head';
import {
  Box,
  Flex,
  Text,
  Card,
  CardHeader,
  CardBody,
  Heading,
  Stack,
  StackDivider,
  Tag,
} from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bags Interview Assessment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box maxW='960px' mx='auto' my={12} border='2px' borderColor='gray.200'>
          <Flex mt='20' align='center' direction='column'>
            <Card>
              <CardHeader>
                <Tag
                  pos='absolute'
                  top='-3'
                  right='5'
                  size='sm'
                  variant='solid'
                  colorScheme='purple'
                >
                  <Text px={5} size='sm'>
                    Good Fit
                  </Text>
                </Tag>
                <Heading float='right' size='md'>
                  Client Report
                </Heading>
              </CardHeader>

              <CardBody>
                <Stack divider={<StackDivider />} spacing='4'>
                  <Box>
                    <Heading size='xs' textTransform='uppercase'>
                      Summary
                    </Heading>
                    <Text pt='2' fontSize='sm'>
                      View a summary of all your clients over the last month.
                    </Text>
                  </Box>
                  <Box>
                    <Heading size='xs' textTransform='uppercase'>
                      Overview
                    </Heading>
                    <Text pt='2' fontSize='sm'>
                      Check out the overview of your clients.
                    </Text>
                  </Box>
                  <Box>
                    <Heading size='xs' textTransform='uppercase'>
                      Analysis
                    </Heading>
                    <Text pt='2' fontSize='sm'>
                      See a detailed analysis of all your business clients.
                    </Text>
                  </Box>
                </Stack>
              </CardBody>
            </Card>
          </Flex>
        </Box>
      </main>
    </div>
  );
};

export default Home;
