import type { NextPage } from 'next';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import {
  Box,
  Flex,
  Text,
  Card,
  CardHeader,
  CardBody,
  Heading,
  Stack,
  StackDivider,
  Highlight,
  Button,
  Tag,
  HStack,
  Spacer,
  Badge,
} from '@chakra-ui/react';
import { Icon } from '@chakra-ui/react';
import { HiOutlineLocationMarker } from 'react-icons/hi';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [windowSize, setWindowSize] = useState(0);

  useEffect(() => {
    // Handler to call on window resize
    const handleResize = () => {
      // Set window width to state
      windowSize !== window.innerWidth
        ? setWindowSize(window.innerWidth)
        : null;
    };

    // Add event listener
    window.addEventListener('resize', handleResize);

    // Call handler right away so state gets updated with initial window size
    handleResize();

    // Remove event listener on cleanup
    return () => window.removeEventListener('resize', handleResize);
  }, [windowSize]); // Re-run the effect if window size changes

  const lorem =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel aliquam aliquam, nisl nisl aliquam nisl, nec aliquam nisl nisl sit amet nisl.';

  const range = (num: number) =>
    Array.from({ length: num }, (value, index) => index);

  const placeholderArr = range(3);

  return (
    <div>
      <Head>
        <title>Bags Interview Assessment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box maxW='960px' mx='auto' my={12}>
          <Flex mt='20' align='center' direction='column'>
            <Card
              variant='elevated'
              border='2px'
              borderColor='#868686'
              style={{
                width: '25rem',
                height: 'auto',
                zIndex: 1,
                backgroundColor: '#FFFFFF',
              }}
            >
              <CardHeader pb={0}>
                <Tag
                  className={styles.purple}
                  pos='absolute'
                  top='-3'
                  right='5'
                  size='sm'
                  variant='solid'
                >
                  <Text px={5} fontSize='14px'>
                    Good Fit
                  </Text>
                </Tag>
                <Text fontSize={['s', 'xl', '2xl']} fontWeight={700}>
                  Revenue Based Financing
                </Text>
              </CardHeader>

              <CardBody p={0} className={styles.shadow} style={{ zIndex: 11 }}>
                <Stack
                  divider={
                    <StackDivider borderColor='#868686' borderWidth={1} />
                  }
                  spacing='4'
                >
                  <Box px={5}>
                    <Text pt='2' fontSize='s' fontWeight='600'>
                      By Lendistry
                    </Text>
                    <Text pt='2' fontSize='s' fontWeight='600'>
                      <Icon as={HiOutlineLocationMarker} mr={2} />
                      Location
                    </Text>
                    <Text pt='2' fontSize='14px' fontWeight='600'>
                      <Highlight
                        query='12 days'
                        styles={{ py: '1', fontWeight: 'bold' }}
                      >
                        Get Funded in 12 days
                      </Highlight>
                    </Text>
                  </Box>
                  <Box style={{ zIndex: 11 }}>
                    <Text
                      style={{ zIndex: 11 }}
                      px={5}
                      pb={2}
                      fontWeight='700'
                      fontSize='22px'
                      className={styles.purpleText}
                    >
                      $10,000 - $1,000,000
                    </Text>
                  </Box>
                </Stack>
              </CardBody>
            </Card>
            <Card
              border='2px'
              borderColor='#C8C6C6'
              style={{
                borderTop: 'none',
                width: '25rem',
                height: 'auto',
                zIndex: -1,
                backgroundColor: '#FFFFFF',
              }}
              top='-10'
            >
              <CardHeader pt={20} pb={0}>
                <HStack spacing={6} direction='row'>
                  <Heading size='md'>About The Lender</Heading>
                  <Spacer />
                  <Button
                    style={{
                      backgroundColor: windowSize <= 1350 ? 'black' : 'blue',
                      color: 'white',
                    }}
                    size='sm'
                    px={5}
                  >
                    <Text fontSize='md' fontWeight='600'>
                      Learn More
                    </Text>
                  </Button>
                </HStack>
              </CardHeader>

              <CardBody p={0}>
                <Stack spacing='4'>
                  <Box px={5}>
                    <Text pt='2' fontSize='xs' fontWeight='600' pb={10}>
                      {lorem}
                    </Text>
                    <Stack direction='column' spacing={4} pb={6}>
                      {placeholderArr.map((item) => (
                        <Tag
                          key={item}
                          className={`${styles.purpleText} ${styles.tag}`}
                          borderRadius='full'
                        >
                          <Text fontSize='16px' fontWeight={700}>
                            Lender Benefit
                          </Text>
                        </Tag>
                      ))}
                    </Stack>
                  </Box>
                </Stack>
              </CardBody>
            </Card>
          </Flex>
        </Box>
      </main>
    </div>
  );
};

export default Home;
