import type { NextPage } from 'next';
import Head from 'next/head';
import {
  Box,
  Flex,
  Text,
  Card,
  CardHeader,
  CardBody,
  Heading,
  Stack,
  StackDivider,
  Highlight,
  Tag,
} from '@chakra-ui/react';
import { Icon } from '@chakra-ui/react';
import { HiOutlineLocationMarker } from 'react-icons/hi';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bags Interview Assessment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box maxW='960px' mx='auto' my={12} border='2px' borderColor='gray.200'>
          <Flex mt='20' align='center' direction='column'>
            <Card variant='elevated' border='2px' borderColor='#868686'>
              <CardHeader pb={0}>
                <Tag
                  pos='absolute'
                  top='-3'
                  right='5'
                  size='sm'
                  variant='solid'
                  colorScheme='purple'
                >
                  <Text px={5} size='sm'>
                    Good Fit
                  </Text>
                </Tag>
                <Heading size='md'>Revenue Based Financing</Heading>
              </CardHeader>

              <CardBody p={0} className={styles.shadow}>
                <Stack
                  divider={
                    <StackDivider borderColor='#868686' borderWidth={1} />
                  }
                  spacing='4'
                >
                  <Box px={5}>
                    <Text pt='2' fontSize='xs' fontWeight='600'>
                      By Lendistry
                    </Text>
                    <Text pt='2' fontSize='xs' fontWeight='600'>
                      <Icon as={HiOutlineLocationMarker} mr={2} />
                      Location
                    </Text>
                    <Text pt='2' fontSize='xs' fontWeight='600'>
                      <Highlight
                        query='12 days'
                        styles={{ py: '1', fontWeight: 'bold' }}
                      >
                        Get Funded in 12 days
                      </Highlight>
                    </Text>
                  </Box>
                  <Box>
                    <Text px={5} fontWeight='700' size='sm' color='purple.500'>
                      $10,000 - $1,000,000
                    </Text>
                  </Box>
                </Stack>
              </CardBody>
            </Card>
            <Card
              border='2px'
              borderColor='#868686'
              style={{borderTop: 'none'}}
              top='3'
            >
              <CardHeader pb={0}>
                <Heading size='md'>Revenue Based Financing</Heading>
              </CardHeader>

              <CardBody p={0} className={styles.shadow}>
                <Stack
                  divider={
                    <StackDivider borderColor='#868686' borderWidth={1} />
                  }
                  spacing='4'
                >
                  <Box px={5}>
                    <Text pt='2' fontSize='xs' fontWeight='600'>
                      By Lendistry
                    </Text>
                    <Text pt='2' fontSize='xs' fontWeight='600'>
                      <Icon as={HiOutlineLocationMarker} mr={2} />
                      Location
                    </Text>
                    <Text pt='2' fontSize='xs' fontWeight='600'>
                      <Highlight
                        query='12 days'
                        styles={{ py: '1', fontWeight: 'bold' }}
                      >
                        Get Funded in 12 days
                      </Highlight>
                    </Text>
                  </Box>
                  <Box>
                    <Text px={5} fontWeight='700' size='sm' color='purple.500'>
                      $10,000 - $1,000,000
                    </Text>
                  </Box>
                </Stack>
              </CardBody>
            </Card>
          </Flex>
        </Box>
      </main>
    </div>
  );
};

export default Home;
